### PR TITLE
Fix return type for `MessageDigest#digest` method

### PR DESCRIPTION
**Pull request by th0r**
Fixes https://github.com/indutny/hash.js/issues/17

### CODE REVIEW

**Comment by indutny** [comment]
Does it depend on encoding? For `hex` it is obviously string, but otherwise is it an array instance?

**Comment by th0r** [comment]
> Does it depend on encoding?

Hmm, I don't know. I thought you're the author of this lib 😉

**Comment by indutny** [comment]
It might be a good time to investigate it then :wink:

**Comment by th0r** [comment]
> but otherwise is it an array instance

Checked the source code - yes, if `enc` is not set it returns `number[]`.

**Comment by indutny** [comment]
Published in 1.1.5

**Pull request merged**
